apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: "flow-voting-tool-backend"
  name: flow-vt-backend-stage-dpy
  namespace: stage
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: "flow-voting-tool-backend"
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: "flow-voting-tool-backend"
    spec:
      containers:
      - image: "bam.brud.local:6000/brudtech/flow-voting-tool-backend:d8c2ba5c44-vt"
        imagePullPolicy: IfNotPresent
        name: "flow-vt-backend-stage-pod"
        ports:
        - containerPort: 5001
          protocol: TCP
        env:
          - name: ENV_NAME
            valueFrom:
              secretKeyRef:
                name: backend-stage-secrets
                key: ENV_NAME
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: backend-stage-secrets
                key: DB_USERNAME
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: backend-stage-secrets
                key: DB_PASSWORD
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: backend-stage-secrets
                key: DB_NAME
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: backend-stage-secrets
                key: DB_HOST
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: backend-stage-secrets
                key: DB_PORT
          - name: IPFS_KEY
            valueFrom:
              secretKeyRef:
                name: backend-stage-secrets
                key: IPFS_KEY
          - name: IPFS_SECRET
            valueFrom:
              secretKeyRef:
                name: backend-stage-secrets
                key: IPFS_SECRET
          - name: FLOW_URL
            valueFrom:
              secretKeyRef:
                name: backend-stage-secrets
                key: FLOW_URL

        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
      - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: "flow-vt-backend-stage-svc"
  namespace: stage
spec:
  type: ClusterIP
  ports:
  - port: 5001
    targetPort: 5001
  selector:
    app: "flow-voting-tool-backend"
    tier: "backend"
    release: "stage"

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: flow-vt-backend-stage-ingress
  namespace: stage

spec:
  rules:
  - host: cast-staging-backend.brud.dev
    http:
      paths:
      - backend:
          service:
            name: backend-stage-svc
            port:
              number: 5001
        path: /
        pathType: Prefix