name: DELETE-TEMP-ENV
on:
  pull_request:
    types: [closed]

env:
  PR_ID: fvtpr${{ github.event.pull_request.number }}
  jenkins_user: ${{ secrets.JENKINS_USER }}
  jenkins_token: ${{ secrets.JENKINS_TOKEN }}
  jenkins_url: ${{ secrets.JENKINS_URL }}

jobs:
  delete-temporal-environment:
    name: Trigger Jenkins Job
    runs-on: ubuntu:20.04
    timeout-minutes: 1

    steps:
      - name: Delete temporal environment by LABEL
        run : |
          curl -X POST https://${{ env.jenkins_user }}:${{ env.jenkins_token }}@${{ env.JENKINS_URL }}/job/DELETE-FLOW-VT/build --data-urlencode json='{"parameter": [{"name":"LABEL", "value":"${{ env.PR_ID }}"}]}'
