name: UPDATE STAGE

on:
  # Trigger the workflow on push or pull request merge
  push:
    branches:
      - FerSanchez/PipelinesChanges

env:
  TAG: ${{ github.sha }}
  db_username: ${{ secrets.DB_USERNAME }}
  db_password: ${{ secrets.DB_PASSWORD }}
  db_hostname: ${{ secrets.DB_HOSTNAME }}
  db_port: ${{ secrets.DB_PORT }}
  db_name: ${{ secrets.DB_NAME }}


jobs:
  build:
    name: Migrations
    runs-on: self-hosted
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: FerSanchez/PipelinesChanges
    
    - name: Install and run migrations
      run: |
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.linux-amd64.tar.gz | tar xvz && sudo mv migrate /usr/local/bin && sudo chmod +x /usr/local/bin/migrate
        sudo migrate -path ./CAST/backend/migrations -database 'postgres://${{ env.db_username }}:${{ env.db_password }}@${{ env.db_hostname }}:${{ env.db_port }}/${{ env.db_name }}?sslmode=disable' -verbose up

